### ISSUE TITLE
Bug: good-fences prevents imports of npm packages

### ISSUE THREAD

**Issue by dgreene1** [smikula/good-fences#51] opened 2018-11-28 15:19 UTC
**Expected Behavior:**
* Per the readme, I expect the following to be true: `If there is no dependencies definition, then any dependency is free to be imported`

**Actual Behavior:**
* With no dependencies specified I can't import a dependency installed with NPM (eh, maybe I used Yarn? I can't remember)

First off let me say that I love the intention of good-fences. Unfortunately when I tried it out it prevented me from importing `lodash` even though my `dependencies` array was empty (I also tried excluding the dependencies config).

The specific error that came up was `Import not allowed` from this line:
https://github.com/smikula/good-fences/blob/af469f97fa0994128eba09c28188b047fe63692a/src/validation/validateImportRules.ts#L42

I found that error message to be strange since `lodash` is a dependency. I believe the issue to be caused by the implementation of good-fences `isExternal` function: https://github.com/smikula/good-fences/blob/9a6e7e763c19aae9ede522f723e798244d163cbe/src/core/ImportRecord.ts#L22

**Comment by smikula** [comment] 2018-11-29 21:36
I think this is a duplicate of #49.  (Are you using Linux/Mac?)  I just published v0.5.1, so give that a try and see if the problem still happens.

**Comment by smikula** [comment] 2019-08-05 19:01
Closing this due to inactivity.

**Closed by smikula** 2019-08-05 19:01 UTC
